---
name: "Bookshelf"
guid: "9c4e63f1-031b-4f25-988b-4f7d78a8b53e"
version: "3.0.0.0"
jellyfin_version: "10.5.0.0"
owner: "jellyfin"
overview: "Manage your books"
description: >
  Supports several different metadata providers and options for
  organizing your collection.
category: "Metadata"
artifacts:
- "Jellyfin.Plugin.Bookshelf.dll"
changelog: >
  changelog
